# High-performance SSD storage (default for app PVCs)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rescuemesh-ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: dobs.csi.digitalocean.com
parameters:
  type: pd-ssd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
# Retained SSD storage (databases)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rescuemesh-ssd-retain
provisioner: dobs.csi.digitalocean.com
parameters:
  type: pd-ssd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
# Economy storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rescuemesh-hdd
provisioner: dobs.csi.digitalocean.com
parameters:
  type: pd-standard
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
