apiVersion: v1
kind: ConfigMap
metadata:
  name: sos-service-config
  namespace: rescuemesh
data:
  NODE_ENV: "production"
  PORT: "3004"
  DB_HOST: "postgres-sos.rescuemesh.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "rescuemesh_sos"
  REDIS_HOST: "redis-sos.rescuemesh.svc.cluster.local"
  REDIS_PORT: "6379"
  RABBITMQ_URL: "amqp://admin:admin@rabbitmq.rescuemesh.svc.cluster.local:5672"
  RABBITMQ_QUEUE_MATCHING: "matching.trigger"
  USER_SERVICE_URL: "http://user-service.rescuemesh.svc.cluster.local:3001"
  SKILL_SERVICE_URL: "http://skill-service.rescuemesh.svc.cluster.local:3002"
  DISASTER_SERVICE_URL: "http://disaster-service.rescuemesh.svc.cluster.local:3003"
  MATCHING_SERVICE_URL: "http://matching-service.rescuemesh.svc.cluster.local:3005"
  SERVICE_TIMEOUT: "5000"
  LOG_LEVEL: "info"
