apiVersion: v1
kind: ConfigMap
metadata:
  name: disaster-service-config
  namespace: rescuemesh
data:
  NODE_ENV: "production"
  PORT: "3003"
  DB_HOST: "postgres-disasters.rescuemesh.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "rescuemesh_disasters"
  SERVICE_TIMEOUT: "5000"
  LOG_LEVEL: "info"
